### ISSUE TITLE
Minigame Concept - Among Us | The Skeld Map

### ISSUE THREAD

**Issue by BehrRiley** [Adriftus-Studios/network-script-data#115]
The game follows a group of crew-mates which, among them, has an impostor (or two) whose goal is to sabotage their space-ship and kill everyone.

The mini-game has potential for adding multiple maps based on the same concepts and has different settings available to configure on a per-game basis. 

---

## Rooms

There are 14 rooms spread across the main map

### Vents

A variety of vent cycles are littered throughout the map:
- Admin, Cafeteria and the hallway above Shields are connected.
- Electrical, MedBay and Security are connected.
- Weapons and Shields are connected to Navigation, respectively.
- Northern Engine and Southern Engine are connected to Reactor, respectively.
 
### Cafeteria

The cafeteria is the spawn point on this map. 
There are five lunch tables.
It is connected to three hallways and has a vent.

**Tasks**:
- [ ] Emergency Meeting button (Center table)
- [x] Empty Garbage (North-East)
- [ ] Download Data (North-East)
- [ ] Fix Wiring (North-West) 

### Weapons

Located to the eastern side of the Cafeteria, the weapons room is connected to two hallways and has a vent.

**Tasks**:
- [ ] Clear Asteroids (Center, Visual Task)
- [ ] Download Data (North-West)
- [ ] Electrical acceptance panel (East)

### Navigation

The navigation room contains the steering and course chart stations as well as an electrical acceptance panel and a data point. 
There is also an electrical wiring panel in the hallway outside Navigation.
There are two vents at the north and south of the room.

**Tasks**:
- [ ] Chart Course (Center Console)
- [ ] Stabilize Steering (North Console)
- [ ] Download Data (North-West) 

### O2

The O2 room houses a trash emptier, an O2vent, and a number pad for fixing the Oxygen Deprivation sabotage. 
This room is connected to a single hallway.

**Tasks**:
- [ ] Clean O2 Filter
- [ ] Empty Chute 

### Shields

The shields room is connected to two hallways and has a vent.

**Tasks**:
- [ ] Shield Primer (South-West, Visual)
- [ ] Electrical acceptance panel 

### Communications

The communications room has a data point, an electrical acceptance panel, and a computer to fix the Comms sabotage.
It is connected to a single hallway.

**Tasks**:
- [ ] Download Data 

### Storage

The storage room has containers in the center of the room, which obstruct vision to the other side.
It is connected to three hallways.

**Tasks**:
- [ ] Fuel Engines - Gas canister
- [ ] Fix Wiring (North-West)
- [ ] Empty Garbage/Chute (South-East, Visual) 

### Admin

The admin room contains a large table in the center of the room, on which is a card-swiper and a map of Players in each room.
The admin room also houses a data upload point, an electrical wiring panel, and a number pad for fixing the Oxygen Deprivation sabotage.
It is connected to one hallway and has a vent.

**Tasks**:
- [x] Swipe Card
- [x] Upload Data 

### Electrical

The electrical room contains the distributor, an electrical divergence panel, an electrical wiring panel, and a data point.
There is also an electrical panel to fix the light sabotage.
It is connected to one hallway and has a vent.

**Tasks**:
- [ ] Divert Power to Communications/Southern Engine/Navigation/O2/Security/Shields/Northern Engine/Weapons (North-West)
- [ ] Fix Wiring (North)
- [ ] Calibrate Distributor (North-East)
- [ ] Download Data 

### Southern Engine

The Southern engine has engine alignment and engine fueling stations and an electrical acceptance panel. It is connected to two hallways and has a vent.

**Tasks**:
- [ ] Fuel Engines 

### Security

The security room has a camera station and one electrical acceptance panel. It is connected to one hallway and has a vent.
Reactor

The reactor contains the reactor starting controls, the reactor manifold controls, and an electrical acceptance panel.
The reactor also has two hand readers to fix the Reactor Meltdown sabotage.
It is connected to one hallway and has two vents.

**Tasks**:
- [ ] Start Reactor
- [ ] Unlock Manifolds (North) 

### Northern Engine

The Northern engine has engine alignment and fueling stations, and an electrical acceptance panel.
It is connected to two hallways and has a vent.

**Tasks**:
- [ ] Align Engine Output
- [ ] Fuel Engines 

### MedBay

The MedBay is connected to one hallway and has a vent.

**Tasks**:
- [ ] Inspect Sample
- [ ] Submit Scan (Visual)

**Comment by BehrRiley** [comment]
I found this image on [Fandom Wikipedia](https://among-us.fandom.com/wiki/Among_Us_Wiki) with a pretty good image reference of the Skeld map as well:

![image](https://media.discordapp.net/attachments/626080540638052382/757482458835845140/latest.png)

**Comment by BehrRiley** [comment]
Updated, more in-depth map reference:
![image](https://cdn.discordapp.com/attachments/626080540638052382/768535209779265636/image0-1.png)

**Comment by ChrispyMC** [comment]
![image](https://user-images.githubusercontent.com/32986257/96765364-10124b80-13a8-11eb-874c-74d50d1bd2e0.png)
This is our agreed method on how to implement vents into the map. The last part (Actionbar title) should be considered as a visual aid.

**Comment by ChrispyMC** [comment]
Do you think we should use the font used in Among Us, now that we have resourcepacks with fonts in them?
